# server:
#   http:
#     addr: 0.0.0.0:8000
#     timeout: 1s
#   grpc:
#     addr: 0.0.0.0:9000
#     timeout: 1s
# data:
#   database:
#     driver: mysql
#     source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
#   redis:
#     addr: 127.0.0.1:6379
#     read_timeout: 0.2s
#     write_timeout: 0.2s

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=172.23.134.110 port=5432 user=postgres password=123456 dbname=realworld sslmode=disable"
  redis:
    addr: 172.23.134.110:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: "123456"
auth:
  jwt_secret: "h3T9!yZ5pR2QmN7bW8xV#uD4sC1aK6jE0tF9@qG8rH2lM5nB7wP3zX6oL4vS1iD8"